/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Custody, CustodyInterface } from "../Custody";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "msg",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "MessageReceived",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_msg",
        type: "string",
      },
    ],
    name: "emitProof",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class Custody__factory {
  static readonly abi = _abi;
  static createInterface(): CustodyInterface {
    return new utils.Interface(_abi) as CustodyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Custody {
    return new Contract(address, _abi, signerOrProvider) as Custody;
  }
}
